### ISSUE TITLE
Use pointer to the WaitGroup to avoid deadlocks

### ISSUE THREAD

**Issue by StarpTech** [ericpauley/broadcast#1]
Hi,
~~you have to use a pointer to the WaitGroup instead a copy to avoid deadlocks.
This is relevant for the examples and tests.~~

This is wrong. It's not the waitGroup but I get a deadlock after executing this example serveral times. It looks like a deadlock in your lib.

Go: go1.9.3 windows/amd64
OS: Windows 10

code
```go
package main

import (
	"sync"
	"time"

	"github.com/starptech/broadcast"
)

func main() {
	var s sync.WaitGroup
	b := make(broadcast.Broadcast)
	s.Add(10)
	for i := 0; i < 10; i++ {
		go func() {
			b.Receive()
			time.Sleep(1 * time.Millisecond)
			s.Done()
		}()
	}
	b <- 1
	s.Wait()
}

```
Trace
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc04201203c)
        C:/Go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc042012030)
        C:/Go/src/sync/waitgroup.go:131 +0x79
main.main()
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:22 +0xfd

goroutine 10 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 11 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 12 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 13 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1
exit status 2
```

**Comment by StarpTech** [comment]
This is wrong. It's not the waitGroup but I get a deadlock after executing this example serveral times. It looks like a deadlock in your lib.

code
```go
package main

import (
	"sync"
	"time"

	"github.com/starptech/broadcast"
)

func main() {
	var s sync.WaitGroup
	b := make(broadcast.Broadcast)
	s.Add(10)
	for i := 0; i < 10; i++ {
		go func() {
			b.Receive()
			time.Sleep(1 * time.Millisecond)
			s.Done()
		}()
	}
	b <- 1
	s.Wait()
}

```
Trace
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc04201203c)
        C:/Go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc042012030)
        C:/Go/src/sync/waitgroup.go:131 +0x79
main.main()
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:22 +0xfd

goroutine 10 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 11 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 12 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 13 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1
exit status 2
```

**Comment by StarpTech** [comment]
It looks like that it can happen that the [`default`](https://github.com/ericpauley/broadcast/blob/d73615ac180a64303a1752764c6a6d585eccc745/broadcast.go#L34) case is executed before the message could be propagated to the others.

**Comment by StarpTech** [comment]
Simpler case to reproduce

```go
	var s sync.WaitGroup
	b := make(broadcast.Broadcast) // Broadcast channels are constructed exactly like regular channels
	s.Add(2)
	go func() {
		b.Receive()
		s.Done()
	}()
	go func() {
		b.Receive()
		s.Done()
	}()
	b <- 1
	s.Wait()
```
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc04204800c)
        C:/Go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc042048000)
        C:/Go/src/sync/waitgroup.go:131 +0x79
main.main()
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:22 +0x112

goroutine 17 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc042044060, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc042044060, 0xc042048000)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:14 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:13 +0xa8
exit status 2
```

**Comment by StarpTech** [comment]
oh, that was a silly mistake. You forgot to close the channel in some tests and in the example which leads to a deadlock.
